import datetime

x = datetime.datetime.now()  # access to now time
print(x)
print(x.date())
print(x.microsecond)
print(x.second)
print(x.minute)
print(x.hour)
print(x.day)
print(x.weekday())
print(x.month)
print(x.year)

y = datetime.datetime(2020, 3, 23, 12, 36, 45, 4324)
print(y)

print(x.strftime("%a"))
print(x.strftime("%A"))
print(x.strftime("%w"))
print(x.strftime("%d"))
print(x.strftime("%b"))
print(x.strftime("%B"))
print(x.strftime("%m"))
print(x.strftime("%y"))
print(x.strftime("%Y"))
print(x.strftime("%H"))
print(x.strftime("%I"))
print(x.strftime("%p"))
print(x.strftime("%M"))
print(x.strftime("%S"))
print(x.strftime("%f"))
print(x.strftime("%z"))
print(x.strftime("%Z"))
print(x.strftime("%j"))
print(x.strftime("%U"))
print(x.strftime("%W"))
print(x.strftime("%c"))
print(x.strftime("%C"))
print(x.strftime("%x"))
print(x.strftime("%X"))
print(x.strftime("%%"))
print(x.strftime("%G"))
print(x.strftime("%u"))
print(x.strftime("%V"))
